# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20170307_0045'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('picture', '0002_inboard_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='inboard',
            unique_together=set([('board', 'picture')]),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('picture', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='picture',
            unique_together=set([('url',)]),
        ),
    ]
