# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20170307_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL Slug'),
        ),
    ]
