# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_picture_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='slug',
            new_name='identification',
        ),
    ]
