# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_auto_20170307_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboard',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='identification',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
