# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cover',
            field=models.ImageField(default='board/none.jpg', upload_to='board'),
        ),
    ]
