# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0004_auto_20170307_0045'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='board',
            unique_together=set([('user', 'name')]),
        ),
    ]
