# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20170308_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
