# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_board_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='url',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
