# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20170309_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='url',
            field=models.CharField(max_length=45),
        ),
    ]
