# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20170309_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='url',
        ),
        migrations.AddField(
            model_name='board',
            name='identification',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL Slug'),
        ),
    ]
